"""
YouTube auto-upload for Krishna Universe via the YouTube Data API v3 + OAuth2.

Credentials are read from environment variables (so they can live in GitHub
Secrets) and written to local files at runtime:
  * YT_CLIENT_SECRET_JSON - the FULL contents of the OAuth client secret JSON
    downloaded from Google Cloud Console (the whole {"installed":{...}} or
    {"web":{...}} object, pasted verbatim).
  * YT_TOKEN_JSON         - the FULL contents of an authorized OAuth token JSON
    (refresh token etc.), e.g. produced by the OAuth Playground or by running
    `python upload_youtube.py --authorize` locally once.

Heavy google-api libraries are imported lazily so importing this module never
hard-fails.
"""

import json
import logging
import os

from .config import BASE_DIR, get_cfg, get_env

log = logging.getLogger("krishna.youtube")

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

CLIENT_SECRET_FILE = os.path.join(str(BASE_DIR), "yt_client_secret.json")
TOKEN_FILE = os.path.join(str(BASE_DIR), "yt_token.json")

# YouTube rejects the request if the tags field exceeds 500 characters in total
# (separators included). Silently overflowing it used to fail the whole upload.
# YouTube's tag limit is 500 for snippet.tags as a whole, and it is enforced on
# the UTF-8 ENCODING, not on the character count. That distinction does not exist
# on an English channel - ASCII is 1 byte per character - but every Devanagari
# character costs 3 bytes, so a tag set that measures a comfortable 385
# "characters" is really 765 bytes and the API rejects the upload with
# reason=invalidTags, location=body.snippet.tags. That is exactly how the first
# real upload failed after the video had already rendered.
#
# YouTube also WRAPS ANY TAG CONTAINING A SPACE IN QUOTES before counting, which
# costs 2 more bytes per multi-word tag. Nearly every tag here is multi-word, so
# that is another ~40 bytes on a full set - budgeted below.
TAGS_BYTE_BUDGET = 460
TAG_MAX_BYTES = 100


def _tag_cost(tag):
    """Bytes this tag will consume in YouTube's 500-byte tag budget.

    UTF-8 length, +1 for the separator, +2 if YouTube has to quote it (which it
    does for any tag containing a space).
    """
    return len(tag.encode("utf-8")) + 1 + (2 if " " in tag else 0)


def _trim_tags(tags):
    """Drop tags from the end until the whole list fits YouTube's tag budget.

    This is deliberately enforced HERE as well as in seo.build_tags, because this
    is the last point before the API call - and it also protects manifest entries
    that were generated by an older build with a wrong budget, which is how the
    first real upload of this channel failed.
    """
    kept = []
    used = 0
    for tag in tags:
        tag = str(tag or "").strip()
        if not tag:
            continue
        # A single overlong tag is dropped rather than allowed to eat the budget.
        if len(tag.encode("utf-8")) > TAG_MAX_BYTES:
            log.warning("Dropping oversized tag (%d bytes): %r",
                        len(tag.encode("utf-8")), tag[:40])
            continue
        cost = _tag_cost(tag)
        if used + cost > TAGS_BYTE_BUDGET:
            continue
        kept.append(tag)
        used += cost
    log.info("Tags: %d kept, %d/%d bytes used.", len(kept), used, TAGS_BYTE_BUDGET)
    return kept


def _materialize_env_json(env_name, dest_path):
    """If an env var holds JSON, write it to dest_path. Returns path or None."""
    raw = get_env(env_name)
    if not raw:
        return dest_path if os.path.exists(dest_path) else None
    try:
        # Validate it parses as JSON before writing.
        json.loads(raw)
    except Exception as exc:
        log.error("%s does not contain valid JSON (%s).", env_name, exc)
        return dest_path if os.path.exists(dest_path) else None
    try:
        with open(dest_path, "w", encoding="utf-8") as fh:
            fh.write(raw)
        log.info("Wrote %s -> %s", env_name, os.path.basename(dest_path))
        return dest_path
    except Exception as exc:
        log.error("Could not write %s (%s).", dest_path, exc)
        return dest_path if os.path.exists(dest_path) else None


def _load_credentials():
    """Build authorized OAuth credentials, refreshing if needed."""
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request

    token_path = _materialize_env_json("YT_TOKEN_JSON", TOKEN_FILE)
    if not token_path or not os.path.exists(token_path):
        log.error(
            "No YouTube token available. Provide YT_TOKEN_JSON or run "
            "`python upload_youtube.py --authorize` locally first."
        )
        return None

    try:
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    except Exception as exc:
        log.error("Could not load token (%s).", exc)
        return None

    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            with open(token_path, "w", encoding="utf-8") as fh:
                fh.write(creds.to_json())
            log.info("Refreshed YouTube OAuth token.")
        except Exception as exc:
            msg = str(exc)
            if "invalid_grant" in msg.lower():
                log.error(
                    "=================================================================\n"
                    "YouTube token refresh FAILED with 'invalid_grant'.\n"
                    "Your YT_TOKEN_JSON refresh token has EXPIRED or been REVOKED, so\n"
                    "no reels can be uploaded until you mint a fresh token.\n"
                    "\n"
                    "Most common cause: the Google OAuth consent screen is still in\n"
                    "'Testing' mode -> refresh tokens die after 7 days.\n"
                    "\n"
                    "FIX:\n"
                    "  1. Google Cloud Console -> APIs & Services -> OAuth consent\n"
                    "     screen -> PUBLISH APP (move from Testing to Production).\n"
                    "  2. Mint a new token (OAuth Playground or `python\n"
                    "     upload_youtube.py --authorize`) signed in with the channel's\n"
                    "     Google account, scope youtube.upload.\n"
                    "  3. Paste the new token JSON into the GitHub Secret\n"
                    "     YT_TOKEN_JSON.\n"
                    "================================================================="
                )
            else:
                log.error("Token refresh failed (%s).", exc)
            return None
    return creds


def authorize():
    """Run a local OAuth flow to mint a token file (interactive, one-time)."""
    from google_auth_oauthlib.flow import InstalledAppFlow

    secret_path = _materialize_env_json("YT_CLIENT_SECRET_JSON", CLIENT_SECRET_FILE)
    if not secret_path or not os.path.exists(secret_path):
        log.error(
            "No client secret found. Provide YT_CLIENT_SECRET_JSON or place "
            "yt_client_secret.json next to this project."
        )
        return None
    flow = InstalledAppFlow.from_client_secrets_file(secret_path, SCOPES)
    creds = flow.run_local_server(port=0)
    with open(TOKEN_FILE, "w", encoding="utf-8") as fh:
        fh.write(creds.to_json())
    log.info("Authorization complete. Token saved to %s", TOKEN_FILE)
    print("\nYT_TOKEN_JSON contents (copy this into your GitHub Secret):\n")
    print(creds.to_json())
    return TOKEN_FILE


def _build_metadata(title, description, tags):
    """Assemble the API request body.

    IMPORTANT: this function no longer force-appends the channel-wide hashtag
    string or the channel-wide default tag list. modules/seo.py now produces a
    per-video hashtag set and tag set at generate time; blindly appending the
    same static block on top of it is exactly what made every upload share an
    identical metadata footprint. The static values survive only as a fallback
    for callers (or old manifest entries) that supply nothing.
    """
    all_tags = list(dict.fromkeys(tags or []))
    if not all_tags:
        all_tags = list(dict.fromkeys(get_cfg("youtube.default_tags", [])))
    all_tags = _trim_tags(all_tags)

    full_desc = (description or "").strip()
    if "#" not in full_desc:
        # No hashtags anywhere in the description -> fall back to the config set.
        fallback = get_cfg(
            "youtube.hashtags",
            "#shorts #कृष्ण #कृष्णकथा #भक्ति",
        )
        if fallback:
            full_desc = (full_desc + "\n\n" + fallback).strip()

    return {
        "snippet": {
            "title": title[:100],
            "description": full_desc[:4900],
            "tags": all_tags,
            "categoryId": str(get_cfg("youtube.category_id", "24")),
            # Declaring the language matters on a Hindi channel. Left unset,
            # YouTube guesses it from the title text; a Hindi video mislabelled
            # as English gets served to the wrong audience and loses automatic
            # title/description translation for other locales.
            "defaultLanguage": get_cfg("youtube.default_language", "hi"),
            "defaultAudioLanguage": get_cfg("youtube.default_audio_language", "hi"),
        },
        "status": {
            "privacyStatus": get_cfg("youtube.privacy_status", "public"),
            "selfDeclaredMadeForKids": bool(get_cfg("youtube.made_for_kids", False)),
        },
    }


def _set_thumbnail(youtube, video_id, thumbnail_path):
    """Attach a custom thumbnail. Best-effort: never fails the upload.

    Shorts do not use the thumbnail inside the Shorts player, but they DO use it
    on the channel's video grid, in the subscriptions feed and in search — which
    is precisely where a browsing viewer decides whether to subscribe.
    """
    from googleapiclient.http import MediaFileUpload

    if not thumbnail_path or not os.path.exists(thumbnail_path):
        return False
    try:
        youtube.thumbnails().set(
            videoId=video_id,
            media_body=MediaFileUpload(thumbnail_path, mimetype="image/jpeg"),
        ).execute()
        log.info("Thumbnail set for %s", video_id)
        return True
    except Exception as exc:
        # Custom thumbnails need a verified channel; log and move on.
        log.warning("Could not set thumbnail (%s).", exc)
        return False


def upload_video(video_path, title, description="", tags=None, privacy=None,
                 thumbnail_path=None):
    """Upload a single video to YouTube. Returns the video id or None."""
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    from googleapiclient.errors import HttpError

    if not os.path.exists(video_path):
        log.error("Video file not found: %s", video_path)
        return None

    creds = _load_credentials()
    if creds is None:
        return None

    body = _build_metadata(title, description, tags)
    if privacy:
        body["status"]["privacyStatus"] = privacy

    try:
        youtube = build("youtube", "v3", credentials=creds)
        media = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)
        request = youtube.videos().insert(
            part="snippet,status", body=body, media_body=media
        )
        log.info("Uploading '%s' to YouTube...", title)
        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                log.info("Upload progress: %d%%", int(status.progress() * 100))
        video_id = response.get("id")
        log.info("Uploaded! https://youtu.be/%s", video_id)
        if thumbnail_path:
            _set_thumbnail(youtube, video_id, thumbnail_path)
        return video_id
    except HttpError as exc:
        status = getattr(getattr(exc, "resp", None), "status", "?")
        content = getattr(exc, "content", b"") or b""
        try:
            detail = content.decode("utf-8", "replace")
        except Exception:
            detail = str(content)
        log.error("YouTube API error (HTTP %s): %s", status, detail[:600] or exc)
        if str(status) == "403" and "quota" in detail.lower():
            log.error(
                "This looks like a QUOTA error. The YouTube Data API allows ~6 "
                "uploads/day on the default 10,000-unit quota. Reduce reels/day "
                "or request a quota increase in Google Cloud Console."
            )
        return None
    except Exception as exc:
        log.error("Upload failed (%s).", exc)
        return None
